language: cpp

matrix:
  include:
    # MacOS Catalina
    - os: osx
      osx_image: xcode12.2
    # MacOS Big Sur
    - os: osx
      osx_image: xcode12.5
    # Ubuntu (Bionic 18.04)
    - os: linux
      compiler: gcc
      dist: bionic
    - os: linux
      compiler: clang
      dist: bionic
    # Ubuntu (Focal 20.04)
    - os: linux
      compiler: gcc
      dist: focal
    - os: linux
      compiler: clang
      dist: focal
    # Windows
    - os: windows

addons:
  apt:
    packages:
      - build-essential
      - nasm
      - libogg-dev
      - libxft-dev
      - libx11-dev
      - libxxf86vm-dev
      - libopenal-dev
      - libfreetype6-dev
      - libxcursor-dev
      - libxinerama-dev
      - libxi-dev
      - libxrandr-dev
      - libxss-dev
      - libglu1-mesa-dev
      - libgtk-3-dev

script:
  - mkdir -p My\ Projects/TestProject/buildFiles/travis/
  - cd My\ Projects/TestProject/buildFiles/travis/
  - cmake ../../../.. -DTORQUE_APP_NAME=TestProject -DCMAKE_BUILD_TYPE=Debug -DTORQUE_TESTING=ON
  - make -j2
  - make install
  - cd ../../game/
  - ls
