<ModuleDefinition
	ModuleId="Core_Utility"
	VersionId="1"
	Description="Module that implements the core engine-level setup for the game."
	ScriptFile="Core_Utility"
	CreateFunction="onCreate"
	DestroyFunction="onDestroy"
	Group="Core">
	<DeclaredAssets
           canSave="true"
           canSaveDynamicFields="true"
           Extension="asset.taml"
           Recurse="true" />
</ModuleDefinition>