<ModuleDefinition
    canSave="true"
    canSaveDynamicFields="true"
    ModuleId="SpaceOrc"
    VersionId="1"
    Group="Game"
    scriptFile="SpaceOrc.cs"
    CreateFunction="onCreate"
    DestroyFunction="onDestroy">
    <DeclaredAssets
        canSave="true"
        canSaveDynamicFields="true"
        Extension="asset.taml"
        Recurse="true" />
    <AutoloadAssets
        canSave="true"
        canSaveDynamicFields="true"
        AssetType="ComponentAsset"
        Recurse="true" />
    <AutoloadAssets
        canSave="true"
        canSaveDynamicFields="true"
        AssetType="GUIAsset"
        Recurse="true" />
</ModuleDefinition>
