<ModuleDefinition
	ModuleId="Core_PostFX"
	VersionId="1"
	Description="Module that implements the core engine-level setup for the game."
	ScriptFile="Core_PostFX"
	CreateFunction="onCreate"
	DestroyFunction="onDestroy"
	Group="Core"
	Dependencies="Core_Rendering=1,Core_Lighting=1">
	<DeclaredAssets
           canSave="true"
           canSaveDynamicFields="true"
           Extension="asset.taml"
           Recurse="true" />
</ModuleDefinition>