# OpenAL module
option(TORQUE_SFX_OPENAL "Use OpenAL SFX" ON)

if(TORQUE_SFX_OPENAL)
  message("Enabling OpenAL Module")
  torqueAddSourceDirectories("${CMAKE_SOURCE_DIR}/Engine/source/sfx/openal")
  if (APPLE)
    torqueAddSourceDirectories("${CMAKE_SOURCE_DIR}/Engine/source/sfx/openal/mac")
  elseif (WIN32)
    torqueAddSourceDirectories("${CMAKE_SOURCE_DIR}/Engine/source/sfx/openal/win32")
  elseif (UNIX)
    torqueAddSourceDirectories("${CMAKE_SOURCE_DIR}/Engine/source/sfx/openal/linux")
  endif()
  find_package(OpenAL CONFIG REQUIRED)
  set(TORQUE_LINK_THIRDPARTY ${TORQUE_LINK_THIRDPARTY} OpenAL::OpenAL)
endif(TORQUE_SFX_OPENAL)