name: Linux Test Results
on:
  workflow_run:
    workflows: ["Linux Build"]
    types:
      - completed

permissions:
    checks: write

jobs:
    checks:
        name: ${{matrix.config.name}}
        runs-on: ${{matrix.config.runos}}
        strategy:
            fail-fast: false
            matrix:
              config: 
              - {
                  name: "Linux Test Results",
                  runos: ubuntu-latest,
                  artifact-name: "torque3dLinuxGCCUnitTest"
                }
              
        steps:
            - name: Download Linux Test Report
              uses: actions/download-artifact@v4
              with:
                path: Linux
                name: ${{matrix.config.artifact-name}}

            - name: Test Reporter
              uses: phoenix-actions/test-reporting@v14
              with:
                artifact: ${{matrix.config.artifact-name}}
                name: ${{matrix.config.name}}
                path: Linux/*.xml
                reporter: java-junit
